# Generated by Django 5.2.8 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_roles_funcionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ciudadano", "Ciudadano"),
                    ("funcionario_municipal", "Funcionario municipal"),
                    ("jefe_cuadrilla", "Jefe de cuadrilla"),
                    ("fiscalizador", "Fiscalizador"),
                    ("administrador", "Administrador"),
                ],
                default="ciudadano",
                max_length=30,
            ),
        ),
    ]
