"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# ========================================
# BASE DIR
# ========================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ========================================
# SECURITY
# ========================================
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-8mfqtdhgfp1-@pum^ehx9pxp*=n5-bcezcr897vazgn(ji$gc^',
)


def str_to_bool(value: str, default: bool = False) -> bool:
    """Convert env strings such as 'true' or '1' to bool."""

    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y"}


DEBUG = str_to_bool(os.environ.get("DJANGO_DEBUG", "True"), default=True)

_default_hosts = "localhost,127.0.0.1,christiangalindez.pythonanywhere.com"
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", _default_hosts).split(",")
    if host.strip()
]

# Needed so that Django accepts POSTs coming from the public domain on PythonAnywhere
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in {"localhost", "127.0.0.1"} and not host.startswith(".")
]

# ========================================
# APPLICATIONS
# ========================================
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'corsheaders',

    # Propias
    'usuarios',
    'denuncias',
    'analitica',
]

# ========================================
# MIDDLEWARE
# ========================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Middleware CORS (debe ir antes de CommonMiddleware)
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ========================================
# URLS / WSGI
# ========================================
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ========================================
# DATABASE
# ========================================
db_engine = os.environ.get("DB_ENGINE", "postgresql").lower()

if db_engine == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.environ.get("SQLITE_NAME", "db.sqlite3"),
        }
    }
elif db_engine == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "microbasurales"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get(
                "DB_HOST", "christiangalindez.mysql.pythonanywhere-services.com"
            ),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": os.environ.get("DB_CHARSET", "utf8mb4"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "microbasurales"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "30102897"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# ========================================
# PASSWORD VALIDATION
# ========================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ========================================
# INTERNATIONALIZATION
# ========================================
LANGUAGE_CODE = 'es-cl'        # ajustado a español de Chile
TIME_ZONE = 'America/Santiago' # horario local

USE_I18N = True
USE_TZ = True


# ========================================
# STATIC FILES
# ========================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ========================================
# POWER BI
# ========================================
POWERBI_DASHBOARD_EMBED_URL = os.environ.get(
    "POWERBI_DASHBOARD_EMBED_URL",
    "https://app.powerbi.com/view?r=eyJrIjoiZGVtby1kYXNoYm9hcmQiLCJuIjoiYXBwLXBvd2VyYmktbWljcm9iYXN1cmFsZXMiLCJ0IjoxfQ%3D%3D",
)


# ========================================
# DEFAULTS
# ========================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'


# ========================================
# DJANGO REST FRAMEWORK + JWT
# ========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Configuración JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGIN_URL = 'login_django'
LOGIN_REDIRECT_URL = 'home_ciudadano'
LOGOUT_REDIRECT_URL = 'login_django'
# ========================================
# CORS (Cross-Origin Resource Sharing)
# ========================================
CORS_ALLOW_ALL_ORIGINS = True  # durante desarrollo, luego restringir


