# Generated by Django 5.2.8 on 2025-11-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denuncia",
            name="titulo",
        ),
    ]
