# Generated by Django 5.2.8 on 2025-11-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "denuncias",
            "0004_merge_0003_denuncia_campos_gestion_0003_denuncia_direccion_textual",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="cuadrilla_asignada",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Equipo responsable de la gestión de la denuncia.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="direccion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dirección referencial del evento reportado.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="zona",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sector o zona operativa asignada por el municipio.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="DenunciaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.CharField(max_length=255)),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En proceso"),
                            ("resuelta", "Resuelta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="denuncias.denuncia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_denuncia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_creacion",),
            },
        ),
    ]
