# Generated by Django 5.2.8 on 2025-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0005_alter_denuncia_cuadrilla_asignada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Nueva"),
                    ("en_proceso", "En gestión"),
                    ("resuelta", "Finalizada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="denuncianotificacion",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("pendiente", "Nueva"),
                    ("en_proceso", "En gestión"),
                    ("resuelta", "Finalizada"),
                ],
                max_length=20,
            ),
        ),
    ]
