# Generated by Django 5.2.8 on 2025-11-17 14:23

from django.db import migrations


def create_notificacion_table(apps, schema_editor):
    """Crea la tabla de notificaciones si aún no existe."""

    connection = schema_editor.connection
    table_names = set(connection.introspection.table_names())
    model = apps.get_model("denuncias", "DenunciaNotificacion")
    table_name = model._meta.db_table

    if table_name in table_names:
        # La tabla ya existe y no es necesario hacer nada.
        return

    schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0006_alter_denuncia_estado_and_more"),
    ]

    operations = [
        migrations.RunPython(create_notificacion_table, migrations.RunPython.noop),
    ]
