# Generated by Django 5.2.8 on 2025-11-18 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0008_denuncia_reporte_cuadrilla_and_state_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteCuadrilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_trabajo", models.ImageField(upload_to="reportes_cuadrilla/")),
                ("comentario", models.TextField()),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                (
                    "denuncia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="denuncias.denuncia",
                    ),
                ),
                (
                    "jefe_cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_cuadrilla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_reporte",),
            },
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="reporte_cuadrilla",
            field=models.OneToOneField(
                blank=True,
                help_text="Reporte final subido por la cuadrilla municipal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="denuncias.reportecuadrilla",
            ),
        ),
    ]
