# Generated by Django 5.2.8 on 2025-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0009_reportecuadrilla_alter_denuncia_reporte_cuadrilla"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="motivo_rechazo",
            field=models.TextField(
                blank=True,
                help_text="Motivo detallado cuando la denuncia ha sido rechazada.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("rechazada", "Rechazada"),
                    ("en_gestion", "En gestión"),
                    ("operativo_realizado", "Operativo realizado"),
                    ("finalizado", "Finalizado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="denuncianotificacion",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("rechazada", "Rechazada"),
                    ("en_gestion", "En gestión"),
                    ("operativo_realizado", "Operativo realizado"),
                    ("finalizado", "Finalizado"),
                ],
                max_length=20,
            ),
        ),
    ]
