# Generated by Django 5.2.8 on 2025-11-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0009_reportecuadrilla_alter_denuncia_reporte_cuadrilla"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denuncia",
            name="reporte_cuadrilla",
        ),
        migrations.AlterField(
            model_name="reportecuadrilla",
            name="denuncia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_reporte_cuadrilla_rel",
                related_query_name="reporte_cuadrilla",
                to="denuncias.denuncia",
            ),
        ),
    ]
