# Generated by Django 5.2.8 on 2025-11-19 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denuncias", "0010_denuncia_motivo_rechazo_alter_denuncia_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado_anterior", models.CharField(max_length=50)),
                ("estado_nuevo", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="historial_registros",
                        to="denuncias.denuncia",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-fecha",)},
        ),
        migrations.AddField(
            model_name="denuncia",
            name="historial",
            field=models.ManyToManyField(blank=True, related_name="denuncias", to="denuncias.historialestado"),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="jefe_cuadrilla_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="denuncias_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
